name: Deploy to VPS

on:
  push:
    branches:
      - main  # Cambia esto si usas otra rama, como "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh -p5992 ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd app  # Ruta donde est치 la aplicaci칩n en la VPS
            git pull origin main  # Actualiza el c칩digo
            bun install           # Instala dependencias 
            sudo systemctl restart mi-app.service   # Reinicia la aplicaci칩n 
          EOF